apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kargo-demo
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  destinations:
  - name: '*'
    namespace: kargo-demo-*
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/jessesuen/kargo-demo.git
  - oci://ghcr.io/jessesuen/charts/otel-app
