apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/jessesuen/kargo-demo.git
      revision: HEAD
      directories:
      - path: env/*
  template:
    metadata:
      name: kargo-demo-{{path.basename}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo:{{path.basename}}
    spec:
      destination:
        namespace: kargo-demo-{{path.basename}}
        name: demo
      project: kargo-demo
      sources:
      - repoURL: oci://ghcr.io/jessesuen/charts/otel-app
        targetRevision: 0.1.0
        path: .
        helm:
          valueFiles:
          - "$values/env/{{path.basename}}/helm/values.yaml"
      - repoURL: https://github.com/jessesuen/kargo-demo.git
        ref: values
