apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: otel-app
  namespace: kargo-demo
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/jessesuen/otel-app
      imageSelectionStrategy: SemVer
  - image:
      repoURL: 541216676946.dkr.ecr.us-west-2.amazonaws.com/lambda-demo/lambda-app
      imageSelectionStrategy: SemVer
