environment: dev

image:
  tag: 0.5.0

replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: kargo-demo-dev.demo.akuity.io
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  LAMBDA_URL: https://irrdy3awgxuhtt3lqacbi3zi3a0hwdri.lambda-url.us-west-2.on.aws/

serviceMonitor:
  enabled: true
  interval: 15s
