environment: dev

image:
  tag: 0.4.0

replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: kargo-demo-dev.demo.akuity.io
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  LAMBDA_URL: https://nmz23yuz26b74euzq73vcs2lte0wjzwv.lambda-url.us-west-2.on.aws/

serviceMonitor:
  enabled: true
  interval: 15s
