environment: dev

image:
  tag: 0.5.0

replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: kargo-demo-dev.demo.akuity.io
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  LAMBDA_URL: https://hkvjzyryd6zc5pk3wdvuwlpgrm0rvzbn.lambda-url.us-west-2.on.aws/

serviceMonitor:
  enabled: true
  interval: 15s
