environment: staging

image:
  tag: 0.3.1

replicaCount: 2

ingress:
  enabled: true
  hosts:
    - host: kargo-demo-staging.demo.akuity.io
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  LAMBDA_URL: https://l3ykbk6yma5snheizugtay6v7m0vrbhf.lambda-url.us-west-2.on.aws/

serviceMonitor:
  enabled: true
  interval: 15s
